/**
 * API response mappers.
 *
 * Prisma stores some array fields as JSON strings. This module converts those
 * strings back into arrays and normalizes enum/status values so that the
 * frontend validation rules always receive the expected shape.
 */

function parseJsonArray(value: unknown): string[] {
  if (Array.isArray(value)) return value;
  if (typeof value === "string" && value.trim().length > 0) {
    try {
      const parsed = JSON.parse(value);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }
  return [];
}

function parseIsoTimestamp(value: unknown): string | undefined {
  if (value instanceof Date) return value.toISOString();
  if (typeof value === "string" && value.trim().length > 0) return value;
  return undefined;
}

function normalizeStatus(
  value: unknown,
  valid: readonly string[]
): string | undefined {
  const str = typeof value === "string" ? value : undefined;
  if (!str) return undefined;
  if (valid.includes(str)) return str;

  // Common aliases generated by older code or seed mistakes
  const aliases: Record<string, string | undefined> = {
    IN_REVIEW: "REVIEW",
    ACTIVE: "NOT_STARTED",
    TODO: "PENDING",
  };
  const mapped = aliases[str];
  return mapped && valid.includes(mapped) ? mapped : undefined;
}

export function mapTask(raw: Record<string, unknown>): Record<string, unknown> {
  return {
    ...raw,
    tags: parseJsonArray(raw.tags),
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
  };
}

export function mapRequirement(
  raw: Record<string, unknown>
): Record<string, unknown> {
  const validStatuses = ["DRAFT", "REVIEW", "APPROVED", "IMPLEMENTED"];
  const status = normalizeStatus(raw.status, validStatuses);

  return {
    ...raw,
    status: status ?? "DRAFT",
    acceptanceCriteria: parseJsonArray(raw.acceptanceCriteria),
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
  };
}

export function mapTestCase(
  raw: Record<string, unknown>
): Record<string, unknown> {
  const validStatuses = ["PENDING", "PASSED", "FAILED", "BLOCKED"];
  const status = normalizeStatus(raw.status, validStatuses);

  return {
    ...raw,
    status: status ?? "PENDING",
    steps: parseJsonArray(raw.steps),
    executedAt:
      parseIsoTimestamp(raw.executedAt) ?? raw.executedAt ?? undefined,
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
  };
}

export function mapBug(raw: Record<string, unknown>): Record<string, unknown> {
  return {
    ...raw,
    status: typeof raw.status === "string" && raw.status ? raw.status : "REPORTED",
    stepsToReproduce: parseJsonArray(raw.stepsToReproduce),
    comments: parseJsonArray(raw.comments),
    attachments: parseJsonArray(raw.attachments),
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
  };
}

export function mapGoal(raw: Record<string, unknown>): Record<string, unknown> {
  const validStatuses = [
    "NOT_STARTED",
    "IN_PROGRESS",
    "ON_TRACK",
    "AT_RISK",
    "ACHIEVED",
  ];
  const status = normalizeStatus(raw.status, validStatuses);

  const mapped = {
    ...raw,
    status: status ?? "NOT_STARTED",
    type: typeof raw.type === "string" && raw.type ? raw.type : "OKR",
    startDate: parseIsoTimestamp(raw.startDate) ?? raw.startDate ?? undefined,
    endDate: parseIsoTimestamp(raw.endDate) ?? raw.endDate ?? undefined,
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
    milestones: Array.isArray(raw.milestones)
      ? raw.milestones.map((m) => mapMilestone(m as Record<string, unknown>))
      : [],
    keyResults: Array.isArray(raw.keyResults)
      ? raw.keyResults.map((k) => mapKeyResult(k as Record<string, unknown>))
      : [],
  };

  return mapped;
}

export function mapMilestone(
  raw: Record<string, unknown>
): Record<string, unknown> {
  return {
    ...raw,
    dueDate: parseIsoTimestamp(raw.dueDate) ?? raw.dueDate ?? undefined,
    completedAt:
      parseIsoTimestamp(raw.completedAt) ?? raw.completedAt ?? undefined,
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
  };
}

export function mapKeyResult(
  raw: Record<string, unknown>
): Record<string, unknown> {
  const validStatuses = ["ON_TRACK", "AT_RISK", "BEHIND"];
  const status = normalizeStatus(raw.status, validStatuses);

  return {
    ...raw,
    status: status ?? "ON_TRACK",
    targetValue:
      typeof raw.targetValue === "number" ? raw.targetValue : Number(raw.targetValue) || 0,
    currentValue:
      typeof raw.currentValue === "number" ? raw.currentValue : Number(raw.currentValue) || 0,
    createdAt: parseIsoTimestamp(raw.createdAt) ?? raw.createdAt,
    updatedAt: parseIsoTimestamp(raw.updatedAt) ?? raw.updatedAt,
  };
}
